# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 08:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0002_auto_20190619_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='jsonPure',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
