# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0003_tvsetting_jsonpure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvsetting',
            name='jsonPure',
        ),
    ]
