# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0004_remove_tvsetting_jsonpure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='jsonPure',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
