# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0005_tvsetting_jsonpure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='color_default_background',
            field=models.CharField(blank=True, default=b'#0096a6', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsetting',
            name='color_search',
            field=models.CharField(blank=True, default=b'#ffaa3f', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsetting',
            name='color_selected_background',
            field=models.CharField(blank=True, default=b'#ffaa3f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color',
            field=models.CharField(blank=True, default=b'#0096a6', max_length=200, null=True),
        ),
    ]
