# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0006_auto_20190625_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='color_text',
            field=models.CharField(blank=True, default=b'#FFFF00FF', max_length=200, null=True),
        ),
    ]
