# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0007_tvsetting_color_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='grid_height',
            field=models.CharField(blank=True, default=b'1.5', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsetting',
            name='grid_width',
            field=models.CharField(blank=True, default=b'2.0', max_length=200, null=True),
        ),
    ]
