# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-06-26 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0008_auto_20190625_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvsetting',
            name='card_height',
            field=models.CharField(blank=True, default=b'1.0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tvsetting',
            name='card_width',
            field=models.CharField(blank=True, default=b'1.0', max_length=200, null=True),
        ),
    ]
