# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0009_auto_20190626_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default=b'#0096a6', max_length=200, null=True)),
                ('Result', models.CharField(blank=True, default=b'#0096a6', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default=b'PlatyerName', max_length=200, null=True)),
            ],
        ),
    ]
