# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0010_match_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Name',
            field=models.CharField(blank=True, default=b'PlayerName', max_length=200, null=True),
        ),
    ]
