# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0011_auto_20190701_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SetWonPlayer1', models.IntegerField(default=0)),
                ('SetWonPlayer2', models.IntegerField(default=0)),
                ('Finished', models.BooleanField(default=False)),
                ('TournamentName', models.CharField(default=b'No Tournamnent', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('Player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player1', to='ebdjango.Player')),
                ('Player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player2', to='ebdjango.Player')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
