# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0012_auto_20190701_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchresult',
            old_name='Finished',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='Player1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='Player2',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='SetWonPlayer1',
            new_name='setWonPlayer1',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='SetWonPlayer2',
            new_name='setWonPlayer2',
        ),
        migrations.RenameField(
            model_name='matchresult',
            old_name='TournamentName',
            new_name='tournament_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Name',
            new_name='name',
        ),
    ]
