# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0013_auto_20190701_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='ebdjango.Player'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='ebdjango.Player'),
        ),
    ]
