# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-01 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0014_auto_20190701_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tournament_name',
            field=models.CharField(default=b'No Tournament', max_length=200),
        ),
    ]
