# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2019-07-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0015_auto_20190701_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='game_type',
            field=models.CharField(choices=[(b'PingPong', b'Ping Pong'), (b'Snooker', b'Snooker')], default=b'Ping Pong', max_length=200),
        ),
    ]
