# Generated by Django 2.0 on 2019-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdjango', '0016_matchresult_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='game_type',
            field=models.CharField(choices=[('Ping Pong', 'Ping Pong'), ('Snooker', 'Snooker')], default='Ping Pong', max_length=200),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='tournament_name',
            field=models.CharField(default='No Tournament', max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, default='PlayerName', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='card_height',
            field=models.CharField(blank=True, default='1.0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='card_width',
            field=models.CharField(blank=True, default='1.0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color',
            field=models.CharField(blank=True, default='#0096a6', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color_default_background',
            field=models.CharField(blank=True, default='#0096a6', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color_search',
            field=models.CharField(blank=True, default='#ffaa3f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color_selected_background',
            field=models.CharField(blank=True, default='#ffaa3f', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='color_text',
            field=models.CharField(blank=True, default='#FFFF00FF', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='grid_height',
            field=models.CharField(blank=True, default='1.5', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='grid_width',
            field=models.CharField(blank=True, default='2.0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tvsetting',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
